var arregloNumeros = new Array(6);
arregloNumeros[0] = 20;
arregloNumeros[1] = 14;
arregloNumeros[2] = 8;
arregloNumeros[3] = 0;
arregloNumeros[4] = 5;
arregloNumeros[4] = 19;
arregloNumeros[5] = 24;
console.log(arregloNumeros[0]);
console.log(arregloNumeros[1]);
console.log(arregloNumeros[2]);
console.log(arregloNumeros[3]);
console.log(arregloNumeros[4]);
console.log(arregloNumeros[5]);
console.log(arregloNumeros[6]);
